"""account profile fields on platform_connections

Revision ID: 0925bf9c1dda
Revises: 80dd1262d984
Create Date: 2026-07-26 20:06:10.885696
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0925bf9c1dda'
down_revision: str | None = '80dd1262d984'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_connections', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('platform_connections', sa.Column('tagline', sa.Text(), nullable=True))
    op.add_column('platform_connections', sa.Column('summary', sa.Text(), nullable=True))
    # Existing rows predate the column and have no skills to put in it, so NOT NULL needs a
    # default at the database level — the Python-side default only applies to new objects.
    op.add_column(
        'platform_connections',
        sa.Column(
            'account_skills',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default='[]',
        ),
    )
    op.add_column('platform_connections', sa.Column('hourly_rate', sa.Float(), nullable=True))
    op.add_column('platform_connections', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('platform_connections', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('platform_connections', sa.Column('portfolio_count', sa.Integer(), nullable=True))
    op.add_column('platform_connections', sa.Column('member_since', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_connections', 'member_since')
    op.drop_column('platform_connections', 'portfolio_count')
    op.drop_column('platform_connections', 'country')
    op.drop_column('platform_connections', 'currency')
    op.drop_column('platform_connections', 'hourly_rate')
    op.drop_column('platform_connections', 'account_skills')
    op.drop_column('platform_connections', 'summary')
    op.drop_column('platform_connections', 'tagline')
    op.drop_column('platform_connections', 'display_name')
    # ### end Alembic commands ###
