"""store marketplace avatar

Revision ID: 0e9756cc88db
Revises: 5de77ec4bf72
Create Date: 2026-07-26 19:26:41.224105
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0e9756cc88db'
down_revision: str | None = '5de77ec4bf72'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_connections', sa.Column('avatar_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_connections', 'avatar_url')
    # ### end Alembic commands ###
