"""competition is scored, not a gate

Revision ID: 2c9c70b71efe
Revises: bfcc752f13ee
Create Date: 2026-07-26 20:28:36.046117
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2c9c70b71efe'
down_revision: str | None = 'bfcc752f13ee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # A rename, not a drop-and-add: the column keeps its value, only its meaning changed. It was
    # a hard cap on bid count; it is now the count at which competition scores half marks.
    op.alter_column(
        'freelancer_profiles', 'max_existing_bids', new_column_name='crowded_at_bids'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'freelancer_profiles', 'crowded_at_bids', new_column_name='max_existing_bids'
    )
    # ### end Alembic commands ###
