"""add accounts, roles and cycle runs

Revision ID: 324bb50b7a30
Revises: 6dbd37c9fb66
Create Date: 2026-07-26 02:25:18.435980
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '324bb50b7a30'
down_revision: str | None = '6dbd37c9fb66'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('drafted', sa.Integer(), nullable=False),
    sa.Column('draft_failures', sa.Integer(), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_runs_started_at'), 'cycle_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_cycle_runs_user_id'), 'cycle_runs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column(
        'users',
        # server_default backfills the rows that already exist; NOT NULL cannot be added to a
        # populated table without one.
        sa.Column('role', sa.String(length=16), nullable=False, server_default='user'),
    )
    op.add_column(
        'users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    op.add_column(
        'users',
        sa.Column('display_name', sa.String(length=120), nullable=False, server_default=''),
    )
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_cycle_runs_user_id'), table_name='cycle_runs')
    op.drop_index(op.f('ix_cycle_runs_started_at'), table_name='cycle_runs')
    op.drop_table('cycle_runs')
    # ### end Alembic commands ###
