"""track bid sync time

Revision ID: 5de77ec4bf72
Revises: d5ffaa230c5e
Create Date: 2026-07-26 18:43:45.937013
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5de77ec4bf72'
down_revision: str | None = 'd5ffaa230c5e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freelancer_profiles', sa.Column('bids_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freelancer_profiles', 'bids_synced_at')
    # ### end Alembic commands ###
