"""one connection per marketplace account

Revision ID: 6415b1f01648
Revises: 0e9756cc88db
Create Date: 2026-07-26 19:34:22.361580
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op


revision: str = '6415b1f01648'
down_revision: str | None = '0e9756cc88db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_connection_user_platform'), 'platform_connections', type_='unique')
    op.create_unique_constraint('uq_connection_user_platform_account', 'platform_connections', ['user_id', 'platform', 'platform_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_connection_user_platform_account', 'platform_connections', type_='unique')
    op.create_unique_constraint(op.f('uq_connection_user_platform'), 'platform_connections', ['user_id', 'platform'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
