"""add bid submission fields

Revision ID: 6dbd37c9fb66
Revises: 41838ee3325d
Create Date: 2026-07-26 01:53:37.875823
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '6dbd37c9fb66'
down_revision: str | None = '41838ee3325d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('bid_amount', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('bid_period_days', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('bid_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('external_bid_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'external_bid_id')
    op.drop_column('jobs', 'bid_submitted_at')
    op.drop_column('jobs', 'bid_period_days')
    op.drop_column('jobs', 'bid_amount')
    # ### end Alembic commands ###
