"""attribute proposals to a marketplace account

Revision ID: 80dd1262d984
Revises: 6415b1f01648
Create Date: 2026-07-26 19:41:07.639309
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '80dd1262d984'
down_revision: str | None = '6415b1f01648'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('connection_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_proposals_connection_id'), 'proposals', ['connection_id'], unique=False)
    op.create_foreign_key(None, 'proposals', 'platform_connections', ['connection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_index(op.f('ix_proposals_connection_id'), table_name='proposals')
    op.drop_column('proposals', 'connection_id')
    # ### end Alembic commands ###
