"""selected account flag on connections

Revision ID: bfcc752f13ee
Revises: 0925bf9c1dda
Create Date: 2026-07-26 20:20:27.992314
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'bfcc752f13ee'
down_revision: str | None = '0925bf9c1dda'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows predate the column; NOT NULL needs a database-level default, since the
    # Python-side one only applies to newly constructed objects.
    op.add_column(
        'platform_connections',
        sa.Column('is_selected', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index('uq_selected_connection_per_user', 'platform_connections', ['user_id'], unique=True, postgresql_where=sa.text('is_selected'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_selected_connection_per_user', table_name='platform_connections', postgresql_where=sa.text('is_selected'))
    op.drop_column('platform_connections', 'is_selected')
    # ### end Alembic commands ###
