"""track content changes on projects and recommendations

Revision ID: d5ffaa230c5e
Revises: fe9ff25d5e64
Create Date: 2026-07-26 18:11:30.845096
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd5ffaa230c5e'
down_revision: str | None = 'fe9ff25d5e64'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('projects', sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recommendations', sa.Column('has_changes', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('recommendations', sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_recommendations_has_changes'), 'recommendations', ['has_changes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_has_changes'), table_name='recommendations')
    op.drop_column('recommendations', 'changed_at')
    op.drop_column('recommendations', 'has_changes')
    op.drop_column('projects', 'last_changed_at')
    op.drop_column('projects', 'content_hash')
    # ### end Alembic commands ###
